---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: helloworld-tf
spec:
  interval: 1m
  url: https://github.com/martinkariuki/tf-controller-helloworld  
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld-tf
spec:
  path: ./terraform
  approvePlan: ""
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: helloworld-tf
  writeOutputsToSecret:
    name: helloworld-outputs

---
apiVersion: infra.contrib. fluxcd.io/vlalphal
kind: Terraform
metadata:
  name: azure-config 
  namespace: flux-system
  annotations: 
    metadata.weave.works/description: This is a sample set of objects for Azure such as role binding
spec:
  interval: 10m 
  approvePlan: auto
  path: ./terraform
  sourceRef:
    kind: GitRepository
    name: helloworld-tf
  runnerPodTemplate:
    spec: 
      envFrom:
      - secretRef:
          name: azure-tf-credentials
  enableInventory: true
