---
apiVersion: infra.contrib. fluxcd.io/vlalphal
kind: Terraform
metadata:
  name: azure-config 
  namespace: flux-system
  annotations: 
    metadata.weave.works/description: This is a sample set of objects for Azure such as role binding
spec:
  interval: 10m 
  approvePlan: auto
  path: ./terraform/azure-config
  sourceRef:
    kind: GitRepository
    name: flux-system 
  runnerPodTemplate:
    spec: 
      envFrom:
      - secretRef:
          name: azure-tf-credentials
  enableInventory: true
